### ISSUE TITLE
1.12.2启动不能

### ISSUE THREAD

**Issue by KirisameY** [Codex-in-somnio/LaunchHelper#6]
07.07 00:17:04 [服务器] 信息 [LH] 
07.07 00:17:04 [服务器] 信息 [LH]     //       ////   //  //  //  //   /////  //  //
07.07 00:17:04 [服务器] 信息 [LH]    //      //  //  //  //  /// //  //      //  //  ___
07.07 00:17:04 [服务器] 信息 [LH]   //      //////  //  //  // ///  //      //////  ____
07.07 00:17:04 [服务器] 信息 [LH]  //      //  //  //  //  //  //  //      //  //  _____
07.07 00:17:04 [服务器] 信息 [LH] //////  //  //   ////   //  //   /////  //  //  ______
07.07 00:17:04 [服务器] 信息 [LH] 
07.07 00:17:04 [服务器] 信息 [LH]       //  //  //////  //      /////   //////  /////
07.07 00:17:04 [服务器] 信息 [LH]      //  //  //      //      //  //  //      //  //  ___
07.07 00:17:04 [服务器] 信息 [LH]     //////  /////   //      /////   /////   /////   ____
07.07 00:17:04 [服务器] 信息 [LH]    //  //  //      //      //      //      //  //  _____
07.07 00:17:04 [服务器] 信息 [LH]   //  //  //////  //////  //      //////  //  //  ______
07.07 00:17:04 [服务器] 信息 [LH] 
07.07 00:17:04 [服务器] 信息 [LH] ====================================================
07.07 00:17:04 [服务器] 信息 [LH] LaunchHelper (0.1) Created with ♥ by Codex in Somnio
07.07 00:17:04 [服务器] 信息 [LH] https://github.com/Codex-in-somnio/LaunchHelper
07.07 00:17:04 [服务器] 信息 [LH] ====================================================
07.07 00:17:04 [服务器] 信息 [LH] 
07.07 00:17:04 [服务器] 信息 [LH] Loading executable Jar forge-1.12.2-14.23.5.2860.jar
07.07 00:17:04 [服务器] 信息 [LH] Loading Java agent authlib-injector-1.1.46.jar=https://mcskin.cn/api/yggdrasil
07.07 00:17:04 [服务器] 信息 [authlib-injector] [INFO] Logging file: /authlib-injector.log
07.07 00:17:04 [服务器] 信息 [authlib-injector] [INFO] Launched from agentmain
07.07 00:17:04 [服务器] 信息 [authlib-injector] [INFO] Version: 1.1.46
07.07 00:17:04 [服务器] 信息 [authlib-injector] [INFO] Authentication server: https://mcskin.cn/api/yggdrasil
07.07 00:17:05 [服务器] 信息 [authlib-injector] [INFO] Attempt to retransform all classes
07.07 00:17:05 [服务器] 信息 [authlib-injector] [INFO] Retransformed 44 classes in 52ms
07.07 00:17:08 [服务器] 信息 2022-07-06 16:17:08,091 main WARN Disabling terminal, you're running in an unsupported environment.
07.07 00:17:08 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
07.07 00:17:08 [服务器] main/信息 [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
07.07 00:17:08 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
07.07 00:17:08 [服务器] main/信息 [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
07.07 00:17:08 [服务器] main/信息 [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:3.10.0-957.12.2.el7.x86_64, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
07.07 00:17:08 [服务器] main/信息 [FML]: Searching /./mods for mods
07.07 00:17:09 [服务器] main/信息 [FML]: Searching /./mods/1.12.2 for mods
07.07 00:17:09 [服务器] main/信息 [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [不昂贵]NE-1.12.2-Forge-1.1.1.jar
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in [堆叠]StackUp-0.2.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in [大地图]XaerosWorldMap_1.22.0_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod XaeroWorldMapPlugin (xaero.map.core.XaeroWorldMapPlugin) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in [更多附魔]SoManyEnchantments-0.5.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod com.Shultrea.Rin.Transformer.CoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod SoManyEnchantments ASM (com.Shultrea.Rin.Transformer.CoreLoader) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in [滑翔伞]Paraglider-1.12.2-1.0.1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod ParagliderLoadingPlugin (com.tictim.paraglider.asm.ParagliderLoadingPlugin) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod ItemPatchingLoader (com.creativemd.itemphysic.ItemPatchingLoader) is not signed!
07.07 00:17:09 [服务器] main/信息 [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [瓦尔基里天空]ValkyrienSkies-1.12.2-1.0-alpha-1.jar
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in [红石供能]RedstoneMinusRedstone-0.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod RedstoneMinusCore (pl.asie.redstoneminus.core.RedstoneMinusCore) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod me.towdium.jecharacters.core.JechCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod JechCore (me.towdium.jecharacters.core.JechCore) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
07.07 00:17:09 [服务器] main/WARN [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
07.07 00:17:09 [服务器] main/信息 [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5.jar
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
07.07 00:17:09 [服务器] main/信息 [mixin]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=file:/./mods/%5B不昂贵%5DNE-1.12.2-Forge-1.1.1.jar Service=LaunchWrapper Env=SERVER
07.07 00:17:09 [服务器] main/WARN [FML]: The coremod MixinLoaderForge (org.valkyrienskies.mixin.MixinLoaderForge) is not signed!
07.07 00:17:09 [服务器] main/信息 [STDOUT]: [org.valkyrienskies.mixin.MixinLoaderForge:<init>:32]: 
07.07 00:17:09 [服务器] 信息 Valkyrien Skies mixin init
07.07 00:17:09 [服务器] main/信息 [mixin]: Compatibility level set to JAVA_8
07.07 00:17:09 [服务器] main/ERROR [mixin]: Mixin config mixins.valkyrienskies.json does not specify "minVersion" property
07.07 00:17:09 [服务器] main/信息 [STDOUT]: [org.valkyrienskies.mixin.MixinLoaderForge:<init>:36]: searge
07.07 00:17:09 [服务器] main/WARN [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
07.07 00:17:09 [服务器] main/信息 [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
07.07 00:17:09 [服务器] main/信息 [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: Forge server detected, skipping class transformer
07.07 00:17:09 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:12 [服务器] main/信息 [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
07.07 00:17:12 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:12 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:12 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:12 [服务器] main/信息 [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
07.07 00:17:12 [服务器] main/ERROR [mixin]: Mixin config mixins.noexpensive.json does not specify "minVersion" property
07.07 00:17:12 [服务器] main/ERROR [mixin]: Mixin config mixins.valkyrienskies.json does not specify "minVersion" property
07.07 00:17:12 [服务器] main/信息 [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@61fe30
07.07 00:17:12 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
07.07 00:17:13 [服务器] main/信息 [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
07.07 00:17:13 [服务器] main/信息 [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
07.07 00:17:14 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.entity.player.EntityPlayer
07.07 00:17:14 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.NetHandlerPlayServerPatch:patchCreativeInventory:51]: Patched processCreativeInventoryAction count check!
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Transforming NetHandlerPlayServer
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Applying Transformation to method (Names [update, func_73660_a] Descriptor ()V)
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Attempting to insert: Update hook
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Patch result: Success
07.07 00:17:14 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.server.management.PlayerList
07.07 00:17:14 [服务器] main/WARN [FML]: ****************************************
07.07 00:17:14 [服务器] main/WARN [FML]: * Not applyingorg.valkyrienskies.mixin.spongepowered.common.network.MixinPacketUtil because Sponge isn't loaded!
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.valkyrienskies.mod.common.MixinLoadManager.shouldApplyMixin(MixinLoadManager.java:56)
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:902)
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:890)
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:865)
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809)
07.07 00:17:14 [服务器] main/WARN [FML]: *  at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569)...
07.07 00:17:14 [服务器] main/WARN [FML]: ****************************************
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Transforming World
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntities, func_72939_s] Descriptor ()V)
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Attempting to insert: Update hook
07.07 00:17:14 [服务器] main/信息 [LibrarianLib ASM]: Patch result: Success
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntityWithOptionalForce, func_72866_a] Descriptor (Lnet/minecraft/entity/Entity;Z)V)
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Attempting to insert: Update hook
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Patch result: Success
07.07 00:17:15 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.world.chunk.Chunk
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Transforming World
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntities, func_72939_s] Descriptor ()V)
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Attempting to insert: Update hook
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Patch result: Success
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntityWithOptionalForce, func_72866_a] Descriptor (Lnet/minecraft/entity/Entity;Z)V)
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Attempting to insert: Update hook
07.07 00:17:15 [服务器] main/信息 [LibrarianLib ASM]: Patch result: Success
07.07 00:17:16 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.server.management.PlayerList
07.07 00:17:16 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.entity.player.EntityPlayer
07.07 00:17:17 [服务器] main/信息 [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
07.07 00:17:18 [服务器] main/信息 [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [itemphysic] Patched net.minecraft.entity.item.EntityItem ...
07.07 00:17:19 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.ItemStackPatch:patchCountGetSet:58]: Patched ItemStack Count getter!
07.07 00:17:19 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.ItemStackPatch:patchCountGetSet:86]: Patched ItemStack Count setter!
07.07 00:17:19 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityDispenser -> func_70297_j_!
07.07 00:17:20 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityChest -> func_70297_j_!
07.07 00:17:21 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityFurnace -> func_70297_j_!
07.07 00:17:21 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityBrewingStand -> func_70297_j_!
07.07 00:17:21 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityHopper -> func_70297_j_!
07.07 00:17:22 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/tileentity/TileEntityShulkerBox -> func_70297_j_!
07.07 00:17:22 [服务器] main/信息 [STDOUT]: [com.Shultrea.Rin.Transformer.SMEASM:transform:54]: Patching EnchantmentProtection
07.07 00:17:23 [服务器] main/信息 [STDOUT]: [pl.asie.stackup.core.MaxStackConstantPatch:lambda$patchMaxLimit$0:53]: Patched max stack check in net/minecraft/entity/item/EntityMinecartContainer -> func_70297_j_!
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Callback Metafactory Transformer]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Httpd is running on port 44201
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Callback Metafactory Transformer]
07.07 00:17:24 [服务器] 信息 [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
07.07 00:17:25 [服务器] main/信息 [STDOUT]: [xaero.map.core.transformer.ClassNodeTransformer:transform:26]: Transforming class net.minecraft.world.storage.SaveFormatOld
07.07 00:17:25 [服务器] 服务器 thread/信息 [minecraft/DedicatedServer]: 开启Minecraft服务器版本: 1.12.2
07.07 00:17:25 [服务器] 信息 Exception in thread "Server console handler" [16:17:25] [Server console handler/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: org/jline/reader/EndOfFileException
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:99)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: org.jline.reader.EndOfFileException
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
07.07 00:17:25 [服务器] Server console handler/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 1 more
07.07 00:17:25 [服务器] 服务器 thread/信息 [FML]: MinecraftForge v14.23.5.2860 Initialized
07.07 00:17:25 [服务器] 服务器 thread/信息 [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
07.07 00:17:25 [服务器] 服务器 thread/信息 [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
07.07 00:17:25 [服务器] 服务器 thread/信息 [FML]: Replaced 1227 ore ingredients
07.07 00:17:25 [服务器] 服务器 thread/信息 [minecraft/MinecraftServer]: 服务器关闭中
07.07 00:17:25 [服务器] 服务器 thread/信息 [minecraft/MinecraftServer]: Saving worlds
07.07 00:17:25 [服务器] 信息 Exception in thread "Server thread" [16:17:25] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
07.07 00:17:25 [服务器] 服务器 thread/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
07.07 00:17:25 [服务器] 服务器 thread/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
07.07 00:17:25 [服务器] 服务器 thread/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
07.07 00:17:25 [服务器] 服务器 thread/信息 [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
07.07 00:17:25 [服务器] 服务器 Shutdown Thread/信息 [minecraft/MinecraftServer]: 服务器关闭中
07.07 00:17:25 [服务器] 服务器 Shutdown Thread/信息 [minecraft/MinecraftServer]: Saving worlds
07.07 00:17:26 [面板] 服务器停止 (starting)
07.07 00:17:26 [面板] Restarting crashed server in 300 seconds
07.07 00:17:26 [面板] 服务器已经关闭

**Comment by KirisameY** [comment]
原版forge和带上参数均正常，本地也是同样的莫名报错

**Comment by AllenBlockChicken** [comment]
我的问题和你基本上完全一样QAQ
